using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace WebAppMvc.Services.Base
{
    //partial allows more than one file with same interface or class name, they merge at run-time--- all must be in same namespace
    //interface is seen in ServiceClient file generated by NSwag for client UI
    public partial interface IClient
    {
        public HttpClient HttpClient { get; }
    }
}
